"""Precomputed demo data of the served household (no model run).

`plegma_101.json` is generated by `make demo-snapshot` in nilmformer-experiment from paper/data:
household profile, evaluation against the sub-metered ground truth, monthly / daily energy and
one sample day. The predicted 1-minute series itself is in the database (households/import).
"""
import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.core.config import settings


@lru_cache
def snapshot() -> dict[str, Any] | None:
    p = Path(settings.DEMO_SNAPSHOT_PATH)
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None
