from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    PROJECT_NAME: str = "WattPrint API"
    API_V1_PREFIX: str = "/api/v1"
    BACKEND_CORS_ORIGINS: list[str] = []

    # NILM inference service (nilmformer-experiment, `docker compose up -d inference`)
    NILM_SERVICE_URL: str = "http://host.docker.internal:8002"

    # demo API (/demo): one household, precomputed results only (no model run)
    DEMO_HOUSEHOLD: str = "Plegma House 101"  # device name of the imported household
    # generated by `make demo-snapshot` in nilmformer-experiment
    DEMO_SNAPSHOT_PATH: str = "app/demo/plegma_101.json"
    # "now" the mobile app asks about (its DEMO_NOW). At start-up the API computes the app's
    # screens for this instant in the background, so the first request is already cached.
    # Empty disables the warm-up.
    DEMO_WARM_ASOF: str = "2023-08-31T23:59:00Z"
    # The copilot is computed in milliseconds, which feels unlike an assistant. Replies are held
    # back about 1.2 s + 5 ms per character of the answer (capped at 4 s) times this factor.
    # 0 turns the pause off (tests, load checks).
    COPILOT_LATENCY_SCALE: float = 1.0

    POSTGRES_USER: str = "wattprint"
    POSTGRES_PASSWORD: str = "change-me"
    POSTGRES_DB: str = "wattprint"
    POSTGRES_HOST: str = "localhost"
    POSTGRES_PORT: int = 5432

    @property
    def DATABASE_URL(self) -> str:
        return (
            f"postgresql+asyncpg://{self.POSTGRES_USER}:{self.POSTGRES_PASSWORD}"
            f"@{self.POSTGRES_HOST}:{self.POSTGRES_PORT}/{self.POSTGRES_DB}"
        )


settings = Settings()
